version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - iggy

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    assignees:
      - iggy

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees:
      - iggy
