skip-check:
  # Some of these are just wrong, the others are at best nice suggestions
  - CKV_OPENAPI_3
  - CKV_OPENAPI_4
  - CKV_OPENAPI_5
  - CKV_OPENAPI_21
  - CKV_DOCKER_2 # I run this in k8s which doesn't read Dockerfile healthchecks
