misconfigurations:
  - id: AVD-DS-0002
    # paths:
    #   - Dockerfile.local
    statement: This is a local dev file
  - id: DS-0002
    # paths:
    #   - Dockerfile.local
    statement: This is a local dev file
