FROM golang:alpine

RUN apk add --no-cache git gcc musl-dev abuild

RUN go get github.com/githubnemo/CompileDaemon

USER 1000:1000

WORKDIR /app
COPY . .

RUN go mod download

HEALTHCHECK --interval=5m --timeout=10s \
    CMD curl -fs localhost:8888/health/ready

ENTRYPOINT CompileDaemon \
    -build="go build ./cmd/api" \
    -color=true \
    -graceful-kill=true \
    -log-prefix=false \
    -command=./api
