FROM golang:alpine

RUN apk add git gcc musl-dev abuild

RUN go get github.com/githubnemo/CompileDaemon

USER 1000:1000

WORKDIR /app
COPY . .

RUN go mod download

ENTRYPOINT CompileDaemon \
    -build="go build ./cmd/api" \
    -color=true \
    -graceful-kill=true \
    -log-prefix=false \
    -command=./api
