---
version: "3"

tasks:
  # go install github.com/deepmap/oapi-codegen/cmd/oapi-codegen@latest
  generate-openapi:
    sources:
      - openapi/packages.yaml
    generates:
      - internal/openapi/api.gen.go
    cmds:
      - mkdir -p internal/openapi
      - oapi-codegen -package api -o internal/openapi/api.gen.go openapi/packages.yaml
      #- oapi-codegen -generate types -package api -o internal/openapi/types.gen.go openapi/packages.yaml
      #- oapi-codegen -generate client -package api -o internal/openapi/client.gen.go openapi/packages.yaml
      #- oapi-codegen -generate server -package api -o internal/openapi/server.gen.go openapi/packages.yaml
      # - docker run -it --rm -v $PWD:/local openapitools/openapi-generator-cli generate \
      # -i openapi/packages.yaml \
      # -g go \
      # -o /local/gen/packages

  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build ./cmd/api

  test:
    cmds:
      - go test ./cmd/api ./internal/openapi

  # build and push the latest, sha, and version tag
  # this only gets run on tags
  docker:release-prod:
    deps: [generate-openapi]
    cmds:
      - |
        docker build \
          --pull \
          -f Dockerfile \
          --tag ghcr.io/atlascloud/packages:latest \
          --tag ghcr.io/atlascloud/packages:$GITHUB_SHA \
          --tag ghcr.io/atlascloud/packages:$GITHUB_REF \
          --cache-from ghcr.io/atlascloud/packages:latest .
      - docker push ghcr.io/atlascloud/packages --all-tags

  # push with just the sha tagged (no latest or version)
  # this gets run on every push
  # this has a soft dep on the build step, but I don't want to set it here in
  # case I decide to split these docker steps into separate file(s)
  docker:push-sha:
    cmds:
      - docker build --pull -f Dockerfile --tag ghcr.io/atlascloud/packages:$GITHUB_SHA --cache-from ghcr.io/atlascloud/packages:latest .
      - docker push ghcr.io/atlascloud/packages:$GITHUB_SHA

  docker:build:
    deps: [generate-openapi]
    cmds:
      - docker build -f Dockerfile.local -t packages .

  docker:run:
    deps: [docker:build]
    cmds:
      # 8008 is a special port on chromebooks
      # https://www.reddit.com/r/Crostini/wiki/index/well-known-ports
      - docker run -it --rm -v $(pwd):/app -v /srv/packages:/srv/packages -p 8888:8888 packages
