---
name: push sha container tag
"on":
  push:
    branches: ["main"]

permissions: read-all

jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test and push SHA tag
        run: task build docker:push-sha
