---
name: Release Tag
"on":
  push:
    tags:
      - v*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: arduino/setup-task@v1
      - uses: actions/checkout@v3
      - name: Run tests
        run: task test
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        run: |
          env
          task build docker:release-prod
