---
name: Release
"on":
  push:
    tags:
      - v*

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: Wizhi/setup-task@v1
      - uses: actions/checkout@v1
      - run: task test
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: task docker-release-prod
